version: '3.9'

services:
  postgres:
    container_name: lingomate_postgres_container
    image: postgres:bullseye
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-lingomate}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-lingomate}
      POSTGRES_DB: ${MYSQL_DATABASE:-lingomate}
    networks:
      - database
    ports:
      - "25432:5432"
    restart: always

networks:
  database:
    driver: bridge

volumes:
  postgres:
