graphql:
  packages:
    - io.github.lingomate
    - io.github.wickedev.graphql
    - io.github.wickedev.spring.reactive.security.jwt
  altair:
    enabled: true

spring:
  r2dbc:
    url: r2dbc:postgres://127.0.0.1:25432/lingomate
    username: lingomate
    password: lingomate
  sql:
    init:
      enabled: true
      mode: always
      schemaLocations: classpath:/db/schema.sql
  main:
    allow-bean-definition-overriding: true

security:
  jwt:
    algorithm: EC
    issuer: https://graphql-jetpack.github.io
    private-key: classpath:keys/ec256-private.pem
    public-key: classpath:keys/ec256-public.pem
    access-token-expires-in: 1h
    refresh-token-expires-in: 60d

r2dbc:
  migrate:
    resourcesPath: classpath:/db/migration/*.sql

